FROM ubuntu:18.04

RUN apt-get update \
    && apt-get -y install \
    python3 \
    python3-pip \
    clang-format \
    git \
    curl

RUN pip3 install "virtualenv<20.0.0"
RUN pip3 install pre-commit

# COPY . /gt/gtirb-stack-stamp/
# WORKDIR /gt/gtirb-stack-stamp/

# RUN pre-commit run --all-files
