FROM docker.grammatech.com/rewriting/gtirb/ubuntu18-gcc7

RUN apt-get install -y python3-pip && \
    python3 -m pip install --user --upgrade setuptools wheel

WORKDIR /gt/gtirb/build/python
RUN python3 setup.py develop

# COPY . /gt/gtirb-stack-stamp/
# WORKDIR /gt/gtirb-stack-stamp/

# RUN rm -rf gtirb_stack_stamp.egg-info
# RUN python3 setup.py develop
